EMPLOYEES = {
    "EMP-1234": {
        "employee_name": "สมชาย วงศ์สวัสดิ์",
        "department": "Engineering",
        "position": "Senior Software Engineer",
        "years_of_service": 3,
        "annual_used": 4,
        "sick_used": 2,
        "personal_used": 1,
        "carried_over": 2,
        "pending_approval": 1,
        "upcoming_leaves": [
            {
                "type": "annual_leave",
                "start_date": "2025-08-15",
                "end_date": "2025-08-15",
                "status": "pending_approval",
                "approver": "วิภาดา จิตรกุล (Director)",
            }
        ],
    },
    "EMP-2345": {
        "employee_name": "พรพิมล ศรีสุข",
        "department": "Product",
        "position": None,
        "years_of_service": 5,
        "annual_used": 8,
        "sick_used": 1,
        "personal_used": 3,
        "carried_over": 3,
        "pending_approval": 0,
        "upcoming_leaves": [],
    },
    "EMP-3456": {
        "employee_name": "John Smith",
        "department": "Engineering",
        "position": None,
        "years_of_service": 1,
        "annual_used": 3,
        "sick_used": 5,
        "personal_used": 0,
        "carried_over": 0,
        "pending_approval": 0,
        "upcoming_leaves": [],
    },
    "EMP-4567": {
        "employee_name": "นภาพร แก้วมณี",
        "department": "HR",
        "position": None,
        "years_of_service": 7,
        "annual_used": 10,
        "sick_used": 0,
        "personal_used": 2,
        "carried_over": 5,
        "pending_approval": 0,
        "upcoming_leaves": [],
    },
    "EMP-5678": {
        "employee_name": "ธนกร พัฒนกิจ",
        "department": "Finance",
        "position": None,
        "years_of_service": 2,
        "annual_used": 2,
        "sick_used": 3,
        "personal_used": 1,
        "carried_over": 0,
        "pending_approval": 0,
        "upcoming_leaves": [],
    },
}

TICKETS = {
    "IT-2025-0042": {
        "ticket_id": "IT-2025-0042",
        "title": "VPN connection drops frequently",
        "description": "VPN disconnects every 30 minutes even though the 12-hour session limit hasn't been reached.",
        "status": "in_progress",
        "priority": "medium",
        "category": "Network & VPN",
        "created_by": {"employee_id": "EMP-1234", "name": "สมชาย วงศ์สวัสดิ์"},
        "assigned_to": {"employee_id": "EMP-0501", "name": "ธนพล เทคนิค", "team": "IT Infrastructure"},
        "created_at": "2025-07-08T14:30:00+07:00",
        "updated_at": "2025-07-09T11:00:00+07:00",
        "estimated_resolution": "2025-07-11T18:00:00+07:00",
        "comments": [
            {
                "author": "ธนพล เทคนิค",
                "timestamp": "2025-07-09T11:00:00+07:00",
                "message": "กำลังตรวจสอบ WireGuard config ครับ น่าจะเป็นปัญหา keep-alive interval ที่ตั้งต่ำเกินไป",
            }
        ],
        "resolution": None,
    },
    "IT-2025-0043": {
        "ticket_id": "IT-2025-0043",
        "title": "Request for additional monitor",
        "description": "ขอจอเพิ่มอีก 1 จอสำหรับงาน development",
        "status": "assigned",
        "priority": "low",
        "category": "Hardware",
        "created_by": {"employee_id": "EMP-1234", "name": "สมชาย วงศ์สวัสดิ์"},
        "assigned_to": {"employee_id": "EMP-0502", "name": "สุรศักดิ์ ฮาร์ดแวร์", "team": "IT Support"},
        "created_at": "2025-07-08T16:00:00+07:00",
        "updated_at": "2025-07-09T09:00:00+07:00",
        "estimated_resolution": "2025-07-15T18:00:00+07:00",
        "comments": [],
        "resolution": None,
    },
    "IT-2025-0044": {
        "ticket_id": "IT-2025-0044",
        "title": "Cannot access staging environment",
        "description": "ขึ้น 403 Forbidden เมื่อเข้า staging ผ่าน VPN",
        "status": "resolved",
        "priority": "high",
        "category": "Access & Permissions",
        "created_by": {"employee_id": "EMP-3456", "name": "John Smith"},
        "assigned_to": {"employee_id": "EMP-0501", "name": "ธนพล เทคนิค", "team": "IT Infrastructure"},
        "created_at": "2025-07-07T09:15:00+07:00",
        "updated_at": "2025-07-08T13:40:00+07:00",
        "estimated_resolution": "2025-07-08T18:00:00+07:00",
        "comments": [
            {
                "author": "ธนพล เทคนิค",
                "timestamp": "2025-07-08T13:40:00+07:00",
                "message": "เพิ่มสิทธิ์ใน IAM group ให้แล้วครับ ลองใหม่อีกครั้ง",
            }
        ],
        "resolution": "เพิ่ม staging-access group ให้ผู้ใช้แล้ว",
    },
    "IT-2025-0045": {
        "ticket_id": "IT-2025-0045",
        "title": "Laptop keyboard not working",
        "description": "ปุ่มแถวบนของคีย์บอร์ดไม่ตอบสนอง",
        "status": "in_progress",
        "priority": "high",
        "category": "Hardware",
        "created_by": {"employee_id": "EMP-5678", "name": "ธนกร พัฒนกิจ"},
        "assigned_to": {"employee_id": "EMP-0502", "name": "สุรศักดิ์ ฮาร์ดแวร์", "team": "IT Support"},
        "created_at": "2025-07-09T08:20:00+07:00",
        "updated_at": "2025-07-09T15:10:00+07:00",
        "estimated_resolution": "2025-07-12T18:00:00+07:00",
        "comments": [
            {
                "author": "สุรศักดิ์ ฮาร์ดแวร์",
                "timestamp": "2025-07-09T15:10:00+07:00",
                "message": "เตรียมเครื่องสำรองให้แล้วครับ ระหว่างรออะไหล่",
            }
        ],
        "resolution": None,
    },
    "IT-2025-0046": {
        "ticket_id": "IT-2025-0046",
        "title": "Request GitHub access for new project",
        "description": "ขอสิทธิ์เข้าถึง repository ของโปรเจกต์ใหม่",
        "status": "waiting_on_user",
        "priority": "medium",
        "category": "Access & Permissions",
        "created_by": {"employee_id": "EMP-1234", "name": "สมชาย วงศ์สวัสดิ์"},
        "assigned_to": {"employee_id": "EMP-0501", "name": "ธนพล เทคนิค", "team": "IT Infrastructure"},
        "created_at": "2025-07-09T10:00:00+07:00",
        "updated_at": "2025-07-09T16:00:00+07:00",
        "estimated_resolution": None,
        "comments": [
            {
                "author": "ธนพล เทคนิค",
                "timestamp": "2025-07-09T16:00:00+07:00",
                "message": "รบกวนแจ้งชื่อ repository ที่ต้องการเข้าถึงด้วยครับ",
            }
        ],
        "resolution": None,
    },
}